default_context:
  project_name: 'dex-api'
  project_slug: 'dex-api'
  domain_main: 'dex-api.com'
  domain_staging: 'stag.dex-api.com'
  docker_swarm_stack_name_main: 'dex-api-com'
  docker_swarm_stack_name_staging: 'stag-dex-api-com'
  secret_key: 'e385a71523e2f113ea237c26e537baf7c9152257aac9c38e753879441391c1d0'
  first_superuser: 'admin@dex-api.com'
  first_superuser_password: 'a1fa72cde7d4ff8489a92fd7d48905bd7d1400833108c086af159a00957a06a4'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.dex-api.com", "https://stag.dex-api.com", "https://dex-api.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@dex-api.com'
  postgres_password: 'e311aa74b35c9203850426a537c0a1adaecfb458ccbb6cd26d5a15618c683928'
  pgadmin_default_user: 'admin@dex-api.com'
  pgadmin_default_user_password: 'a1fa72cde7d4ff8489a92fd7d48905bd7d1400833108c086af159a00957a06a4'
  traefik_constraint_tag: 'dex-api.com'
  traefik_constraint_tag_staging: 'stag.dex-api.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'a1fa72cde7d4ff8489a92fd7d48905bd7d1400833108c086af159a00957a06a4'
  sentry_dsn: ''
  docker_image_prefix: 'dex-api'
  docker_image_backend: 'dex-api-backend'
  docker_image_celeryworker: 'dex-api-celeryworker'
  docker_image_frontend: 'dex-api-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
